name = "jhm5-ex05"
main = "src/worker.js"
compatibility_date = "2023-10-11"

[site]
bucket = "./apps"

# KV Namespace for Tication app
kv_namespaces = [
  { binding = "TICATION_KV", id = "0c26fa91eaf944c08f189e84498c71b3" }
]

# D1 Database for HKDSE analyzer
[[d1_databases]]
binding = "DB"
database_name = "hkdse_analyzer"
database_id = "01d59737-bc20-4d51-8534-b97a96fa02f0"